# 
# Copyright (c) 2020-2025 IAR Systems AB
#
# Dockerfile for the IAR Build Tools (BX)
#
# See LICENSE for detailed license information
#
#
# These arguments comes from the `build` utility
# Knowingly `safe defaults` are used if not specified otherwise
#
#  - 2022Q3+ IAR toolchains: Ubuntu Linux v20.04 (*default)
#  - earlier IAR toolchains: Ubuntu Linux v18.04
ARG BX_UBUNTU_VERSION=20.04
#
# Stage 1: The Ubuntu base image compatible required by BX
#
FROM ubuntu:${BX_UBUNTU_VERSION} AS base
#
# Copy the installer package from the context to `/tmp`
#
ARG BX_DEB_FILE=bx*-?.??.?.deb
ARG BX_DEV_DEB_FILE=bx*-cspy-device-support*.deb
COPY ${BX_DEB_FILE} ${BX_DEV_DEB_FILE} /tmp/
#
# Install the necessary packages and cleanup
#  sudo                      : required by earlier versions of bx*.deb
#  libsqlite3-0              : required by iarbuild
#  libxml2, tzdata           : required by C-STAT
#  udev, libusb-1.0-0        : required by C-SPY (in bxarm-9.50+)
#
RUN apt-get -qq update > /dev/null && \
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
libsqlite3-0 \
libxml2 tzdata \
udev libusb-1.0-0 usbutils \
> /dev/null



# Install curl and wget
RUN apt-get update && apt-get install -y curl wget

# Define the variable HTTPS_ADDRESS as the download URL
ARG HTTPS_ADDRESS=https://netstorage.iar.com/FileStore/STANDARD/001/003/514/iar-license-server-tools-2.18.3.deb

# Download the iar-license-server-tools installation package
RUN curl -o /tmp/iar-license-server-tools-2.18.3.deb ${HTTPS_ADDRESS}

# Install iar-license-server-tools
RUN sudo dpkg -i /tmp/iar-license-server-tools-2.18.3.deb || \
    (apt-get -qq update > /dev/null && apt-get -qq install -f -y > /dev/null)

# Clean up unnecessary files
RUN rm -f /tmp/iar-license-server-tools-2.18.3.deb

# Set up the IAR License Manager
RUN echo "---- Setting up IAR License Manager ----"

# Ensure license_server_tools exists at the specified path
RUN if [ -d "/opt/iarsystems/license_server_tools/common/bin" ]; then \
    echo "License Server Tools found."; \
  else \
    echo "License Server Tools not found. Please verify your installation."; \
    exit 1; \
  fi

# Start the License Server
RUN sudo /opt/iarsystems/license_server_tools/common/bin/lserv64 || echo "License server might already be running."

# License Renewal
ARG SERIAL_NUMBER=8008-536-827-8737
RUN if [ -n "${SERIAL_NUMBER}" ]; then \
    echo "Renewing license with serial number: ${SERIAL_NUMBER}"; \
    /opt/iarsystems/license_server_tools/common/bin/lightlicensemanager renew "${SERIAL_NUMBER}" || { \
        echo "License renewal failed. Please check the serial number and try again."; exit 1; \
    }; \
  else \
    echo "SERIAL_NUMBER is not provided. Please provide a valid asset name."; \
    exit 1; \
  fi



RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq /tmp/*.deb
ARG BX_INCLUDE_CMAKE
ARG BX_INCLUDE_GIT
ARG BX_INCLUDE_SUDO
RUN test ${BX_INCLUDE_CMAKE} -eq 1 \
&& DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends cmake > /dev/null \
|| echo " **** BX_INCLUDE_CMAKE is [off]."
RUN test ${BX_INCLUDE_GIT} -eq 1 \
&& DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends git > /dev/null \
|| echo " **** BX_INCLUDE_GIT is [off]."
RUN test ${BX_INCLUDE_SUDO} -eq 1 \
&& DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends sudo > /dev/null \
|| echo " **** BX_INCLUDE_SUDO is [off]."
#
# Slimming image
#
ARG BX_PKG_ARCH=arm
ARG BX_EXCLUDE_CMSIS
ARG BX_EXCLUDE_DOCS
ARG BX_EXCLUDE_SRC
ARG BX_EXCLUDE_JPN_FILES
RUN test $BX_EXCLUDE_CMSIS -eq 1 \
&& find /opt/iar* -maxdepth 3 -type d -name CMSIS -exec rm -r {} + \
|| echo " **** BX_EXCLUDE_CMSIS is [off]."
RUN test $BX_EXCLUDE_DOCS -eq 1 \
&& find /opt/iar* -maxdepth 3 -type d -name doc -exec rm -r {} + \
|| echo " **** BX_EXCLUDE_DOCS is [off]."
RUN test $BX_EXCLUDE_SRC -eq 1 \
&& find /opt/iar* -maxdepth 3 -type d -name src -exec rm -r {} +; \
   find /opt/iar* -maxdepth 4 -type d -name template -exec rm -r {} + \
|| echo " **** BX_EXCLUDE_SRC is [off]."
RUN test $BX_EXCLUDE_JPN_FILES -eq 1 \
&& find /opt/iar* -regextype posix-extended -regex '.*\.(JPN|locale.ja_JP)$' -exec rm -r {} + \
|| echo " **** BX_EXCLUDE_JPN_FILES is [off]."
RUN rm -rf /var/lib/apt/lists/* /tmp/*.deb
#
# Patch file modes: post-mortem for earlier installers
#
RUN \
find /opt/iar* -type f -regextype posix-extended \
-iregex '.*(\.(a|bat|board|c|cmake|cpp|css|deb|dat|ew[pdtw]|featureinfo|flash|gif|gitignore|h|html|i|i79|icf|ini|ipp|js|json|ld|m[od]?|mar|menu|out|pdf|png|productinfo|py|rc|rpm|rtebuild|s|sct|scvd|so(\.?[0-9]?).*|src|suc|txt|uvoptx|uvprojx|xml|xsd|zip)|\/inc\/.*|\/src\/.*)$' \
-exec chmod 0644 {} +;
#
# Stage 2: Avoids the /tmp layer, reducing the final image size
#
FROM ubuntu:${BX_UBUNTU_VERSION} AS final
#
# Environment variables
# bx-docker - issue #22 - starting from bxarm-9.30.1, iarbuild tries to create $HOME/.iar.
#                         For the Ubuntu 20.04 container, $HOME must be manually set.
#
ARG BX_PKG_ARCH=arm
ARG BX_ASM_EXEC=iasm
ENV LC_ALL=C \
PATH=/opt/iarsystems/bx$BX_PKG_ARCH/$BX_PKG_ARCH/bin:/opt/iarsystems/bx$BX_PKG_ARCH/common/bin:$PATH \
CC=icc$BX_PKG_ARCH \
CXX=icc$BX_PKG_ARCH \
ASM=$BX_ASM_EXEC$BX_PKG_ARCH \
HOME=/workdir
#
# Copy root dir from `base` to the `final` image
#
COPY --from=base / /
#
# Set working directory in the `final` image
#
WORKDIR ${HOME}
#
# Entrypoint: command invoked when a container starts
#
ENTRYPOINT ["/bin/bash"]
